// <auto-generated />
using System;
using Corkboard.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Corkboard.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251208201634_Seed2Cpw235")]
    partial class Seed2Cpw235
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("Corkboard.Models.Channel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("ServerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ServerId");

                    b.ToTable("Channels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 11, 1, 12, 10, 0, 0, DateTimeKind.Utc),
                            Name = "general",
                            ServerId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 11, 1, 12, 11, 0, 0, DateTimeKind.Utc),
                            Name = "asp-net-core",
                            ServerId = 1
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 11, 1, 12, 12, 0, 0, DateTimeKind.Utc),
                            Name = "csharp-basics",
                            ServerId = 1
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2024, 11, 1, 12, 13, 0, 0, DateTimeKind.Utc),
                            Name = "data-structures",
                            ServerId = 1
                        });
                });

            modelBuilder.Entity("Corkboard.Models.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChannelId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("MessageContent")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("TEXT");

                    b.Property<string>("SenderId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ChannelId");

                    b.HasIndex("SenderId");

                    b.ToTable("Messages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ChannelId = 1,
                            CreatedAt = new DateTime(2024, 11, 3, 8, 0, 0, 0, DateTimeKind.Utc),
                            MessageContent = "Welcome to CPW 235! Share what you want to learn this quarter.",
                            SenderId = "seed-user-cpw-235"
                        },
                        new
                        {
                            Id = 2,
                            ChannelId = 1,
                            CreatedAt = new DateTime(2024, 11, 3, 8, 4, 0, 0, DateTimeKind.Utc),
                            MessageContent = "Drop your favorite dev tool or shortcut.",
                            SenderId = "seed-user-cpw-235-2"
                        },
                        new
                        {
                            Id = 3,
                            ChannelId = 1,
                            CreatedAt = new DateTime(2024, 11, 3, 8, 8, 0, 0, DateTimeKind.Utc),
                            MessageContent = "Reminder: office hours posted in #asp-net-core.",
                            SenderId = "seed-user-cpw-235-3"
                        },
                        new
                        {
                            Id = 4,
                            ChannelId = 1,
                            CreatedAt = new DateTime(2024, 11, 3, 8, 12, 0, 0, DateTimeKind.Utc),
                            MessageContent = "Form study groups here—post your availability.",
                            SenderId = "seed-user-cpw-235-4"
                        },
                        new
                        {
                            Id = 5,
                            ChannelId = 1,
                            CreatedAt = new DateTime(2024, 11, 3, 8, 16, 0, 0, DateTimeKind.Utc),
                            MessageContent = "What topic should we deep dive next week?",
                            SenderId = "seed-user-cpw-235-5"
                        },
                        new
                        {
                            Id = 6,
                            ChannelId = 1,
                            CreatedAt = new DateTime(2024, 11, 3, 8, 20, 0, 0, DateTimeKind.Utc),
                            MessageContent = "Any blockers on the current lab?",
                            SenderId = "seed-user-cpw-235-6"
                        },
                        new
                        {
                            Id = 7,
                            ChannelId = 1,
                            CreatedAt = new DateTime(2024, 11, 3, 8, 24, 0, 0, DateTimeKind.Utc),
                            MessageContent = "Share a win from today, big or small.",
                            SenderId = "seed-user-cpw-235"
                        },
                        new
                        {
                            Id = 8,
                            ChannelId = 1,
                            CreatedAt = new DateTime(2024, 11, 3, 8, 28, 0, 0, DateTimeKind.Utc),
                            MessageContent = "Tips for keeping VS Code tidy?",
                            SenderId = "seed-user-cpw-235-2"
                        },
                        new
                        {
                            Id = 9,
                            ChannelId = 1,
                            CreatedAt = new DateTime(2024, 11, 3, 8, 32, 0, 0, DateTimeKind.Utc),
                            MessageContent = "What podcasts or videos help you learn C#?",
                            SenderId = "seed-user-cpw-235-3"
                        },
                        new
                        {
                            Id = 10,
                            ChannelId = 1,
                            CreatedAt = new DateTime(2024, 11, 3, 8, 36, 0, 0, DateTimeKind.Utc),
                            MessageContent = "If you were teaching, what's one thing you'd change?",
                            SenderId = "seed-user-cpw-235-4"
                        },
                        new
                        {
                            Id = 11,
                            ChannelId = 1,
                            CreatedAt = new DateTime(2024, 11, 3, 8, 40, 0, 0, DateTimeKind.Utc),
                            MessageContent = "Which keyboard shortcut saves you the most time?",
                            SenderId = "seed-user-cpw-235-5"
                        },
                        new
                        {
                            Id = 12,
                            ChannelId = 1,
                            CreatedAt = new DateTime(2024, 11, 3, 8, 44, 0, 0, DateTimeKind.Utc),
                            MessageContent = "Post a meme that sums up your debugging session.",
                            SenderId = "seed-user-cpw-235-6"
                        },
                        new
                        {
                            Id = 13,
                            ChannelId = 1,
                            CreatedAt = new DateTime(2024, 11, 3, 8, 48, 0, 0, DateTimeKind.Utc),
                            MessageContent = "Who wants to pair program tonight?",
                            SenderId = "seed-user-cpw-235"
                        },
                        new
                        {
                            Id = 14,
                            ChannelId = 1,
                            CreatedAt = new DateTime(2024, 11, 3, 8, 52, 0, 0, DateTimeKind.Utc),
                            MessageContent = "Share your go-to snack while coding.",
                            SenderId = "seed-user-cpw-235-2"
                        },
                        new
                        {
                            Id = 15,
                            ChannelId = 1,
                            CreatedAt = new DateTime(2024, 11, 3, 8, 56, 0, 0, DateTimeKind.Utc),
                            MessageContent = "What is your terminal theme?",
                            SenderId = "seed-user-cpw-235-3"
                        },
                        new
                        {
                            Id = 16,
                            ChannelId = 1,
                            CreatedAt = new DateTime(2024, 11, 3, 9, 0, 0, 0, DateTimeKind.Utc),
                            MessageContent = "Drop a screenshot of your current setup.",
                            SenderId = "seed-user-cpw-235-4"
                        },
                        new
                        {
                            Id = 17,
                            ChannelId = 1,
                            CreatedAt = new DateTime(2024, 11, 3, 9, 4, 0, 0, DateTimeKind.Utc),
                            MessageContent = "Best advice you've received about learning to code?",
                            SenderId = "seed-user-cpw-235-5"
                        },
                        new
                        {
                            Id = 18,
                            ChannelId = 1,
                            CreatedAt = new DateTime(2024, 11, 3, 9, 8, 0, 0, DateTimeKind.Utc),
                            MessageContent = "One concept you want reviewed this week?",
                            SenderId = "seed-user-cpw-235-6"
                        },
                        new
                        {
                            Id = 19,
                            ChannelId = 1,
                            CreatedAt = new DateTime(2024, 11, 3, 9, 12, 0, 0, DateTimeKind.Utc),
                            MessageContent = "Favorite NuGet package you discovered recently?",
                            SenderId = "seed-user-cpw-235"
                        },
                        new
                        {
                            Id = 20,
                            ChannelId = 1,
                            CreatedAt = new DateTime(2024, 11, 3, 9, 16, 0, 0, DateTimeKind.Utc),
                            MessageContent = "How do you keep track of tasks and todos?",
                            SenderId = "seed-user-cpw-235-2"
                        },
                        new
                        {
                            Id = 21,
                            ChannelId = 1,
                            CreatedAt = new DateTime(2024, 11, 3, 9, 20, 0, 0, DateTimeKind.Utc),
                            MessageContent = "What helps you focus during deep work?",
                            SenderId = "seed-user-cpw-235-3"
                        },
                        new
                        {
                            Id = 22,
                            ChannelId = 1,
                            CreatedAt = new DateTime(2024, 11, 3, 9, 24, 0, 0, DateTimeKind.Utc),
                            MessageContent = "Share a Git command you rely on daily.",
                            SenderId = "seed-user-cpw-235-4"
                        },
                        new
                        {
                            Id = 23,
                            ChannelId = 1,
                            CreatedAt = new DateTime(2024, 11, 3, 9, 28, 0, 0, DateTimeKind.Utc),
                            MessageContent = "What's confusing about HTTP vs HTTPS?",
                            SenderId = "seed-user-cpw-235-5"
                        },
                        new
                        {
                            Id = 24,
                            ChannelId = 1,
                            CreatedAt = new DateTime(2024, 11, 3, 9, 32, 0, 0, DateTimeKind.Utc),
                            MessageContent = "Any tips for balancing coursework and rest?",
                            SenderId = "seed-user-cpw-235-6"
                        },
                        new
                        {
                            Id = 25,
                            ChannelId = 1,
                            CreatedAt = new DateTime(2024, 11, 3, 9, 36, 0, 0, DateTimeKind.Utc),
                            MessageContent = "Share a bug you solved today.",
                            SenderId = "seed-user-cpw-235"
                        },
                        new
                        {
                            Id = 26,
                            ChannelId = 1,
                            CreatedAt = new DateTime(2024, 11, 3, 9, 40, 0, 0, DateTimeKind.Utc),
                            MessageContent = "What music helps you concentrate?",
                            SenderId = "seed-user-cpw-235-2"
                        },
                        new
                        {
                            Id = 27,
                            ChannelId = 1,
                            CreatedAt = new DateTime(2024, 11, 3, 9, 44, 0, 0, DateTimeKind.Utc),
                            MessageContent = "How do you name variables for clarity?",
                            SenderId = "seed-user-cpw-235-3"
                        },
                        new
                        {
                            Id = 28,
                            ChannelId = 1,
                            CreatedAt = new DateTime(2024, 11, 3, 9, 48, 0, 0, DateTimeKind.Utc),
                            MessageContent = "What is your favorite C# feature?",
                            SenderId = "seed-user-cpw-235-4"
                        },
                        new
                        {
                            Id = 29,
                            ChannelId = 1,
                            CreatedAt = new DateTime(2024, 11, 3, 9, 52, 0, 0, DateTimeKind.Utc),
                            MessageContent = "How do you test your code locally?",
                            SenderId = "seed-user-cpw-235-5"
                        },
                        new
                        {
                            Id = 30,
                            ChannelId = 1,
                            CreatedAt = new DateTime(2024, 11, 3, 9, 56, 0, 0, DateTimeKind.Utc),
                            MessageContent = "Share a small habit that improved your code quality.",
                            SenderId = "seed-user-cpw-235-6"
                        },
                        new
                        {
                            Id = 31,
                            ChannelId = 1,
                            CreatedAt = new DateTime(2024, 11, 3, 10, 0, 0, 0, DateTimeKind.Utc),
                            MessageContent = "Any questions about the upcoming assignment?",
                            SenderId = "seed-user-cpw-235"
                        },
                        new
                        {
                            Id = 32,
                            ChannelId = 1,
                            CreatedAt = new DateTime(2024, 11, 3, 10, 4, 0, 0, DateTimeKind.Utc),
                            MessageContent = "What do you want to build after this class?",
                            SenderId = "seed-user-cpw-235-2"
                        },
                        new
                        {
                            Id = 33,
                            ChannelId = 1,
                            CreatedAt = new DateTime(2024, 11, 3, 10, 8, 0, 0, DateTimeKind.Utc),
                            MessageContent = "Share a helpful doc link you keep bookmarked.",
                            SenderId = "seed-user-cpw-235-3"
                        },
                        new
                        {
                            Id = 34,
                            ChannelId = 1,
                            CreatedAt = new DateTime(2024, 11, 3, 10, 12, 0, 0, DateTimeKind.Utc),
                            MessageContent = "How do you stay organized across projects?",
                            SenderId = "seed-user-cpw-235-4"
                        },
                        new
                        {
                            Id = 35,
                            ChannelId = 1,
                            CreatedAt = new DateTime(2024, 11, 3, 10, 16, 0, 0, DateTimeKind.Utc),
                            MessageContent = "What is one thing you wish you knew earlier about Git?",
                            SenderId = "seed-user-cpw-235-5"
                        },
                        new
                        {
                            Id = 36,
                            ChannelId = 1,
                            CreatedAt = new DateTime(2024, 11, 3, 10, 20, 0, 0, DateTimeKind.Utc),
                            MessageContent = "Favorite VS Code extension right now?",
                            SenderId = "seed-user-cpw-235-6"
                        },
                        new
                        {
                            Id = 37,
                            ChannelId = 1,
                            CreatedAt = new DateTime(2024, 11, 3, 10, 24, 0, 0, DateTimeKind.Utc),
                            MessageContent = "How do you approach refactoring safely?",
                            SenderId = "seed-user-cpw-235"
                        },
                        new
                        {
                            Id = 38,
                            ChannelId = 1,
                            CreatedAt = new DateTime(2024, 11, 3, 10, 28, 0, 0, DateTimeKind.Utc),
                            MessageContent = "Share a CSS trick you like.",
                            SenderId = "seed-user-cpw-235-2"
                        },
                        new
                        {
                            Id = 39,
                            ChannelId = 1,
                            CreatedAt = new DateTime(2024, 11, 3, 10, 32, 0, 0, DateTimeKind.Utc),
                            MessageContent = "What error message have you seen too often?",
                            SenderId = "seed-user-cpw-235-3"
                        },
                        new
                        {
                            Id = 40,
                            ChannelId = 1,
                            CreatedAt = new DateTime(2024, 11, 3, 10, 36, 0, 0, DateTimeKind.Utc),
                            MessageContent = "How do you handle merge conflicts?",
                            SenderId = "seed-user-cpw-235-4"
                        },
                        new
                        {
                            Id = 41,
                            ChannelId = 1,
                            CreatedAt = new DateTime(2024, 11, 3, 10, 40, 0, 0, DateTimeKind.Utc),
                            MessageContent = "One networking concept you want clarified?",
                            SenderId = "seed-user-cpw-235-5"
                        },
                        new
                        {
                            Id = 42,
                            ChannelId = 1,
                            CreatedAt = new DateTime(2024, 11, 3, 10, 44, 0, 0, DateTimeKind.Utc),
                            MessageContent = "Share a shortcut for navigating files quickly.",
                            SenderId = "seed-user-cpw-235-6"
                        },
                        new
                        {
                            Id = 43,
                            ChannelId = 1,
                            CreatedAt = new DateTime(2024, 11, 3, 10, 48, 0, 0, DateTimeKind.Utc),
                            MessageContent = "What part of SOLID is still fuzzy?",
                            SenderId = "seed-user-cpw-235"
                        },
                        new
                        {
                            Id = 44,
                            ChannelId = 1,
                            CreatedAt = new DateTime(2024, 11, 3, 10, 52, 0, 0, DateTimeKind.Utc),
                            MessageContent = "Any strategies for naming branches?",
                            SenderId = "seed-user-cpw-235-2"
                        },
                        new
                        {
                            Id = 45,
                            ChannelId = 1,
                            CreatedAt = new DateTime(2024, 11, 3, 10, 56, 0, 0, DateTimeKind.Utc),
                            MessageContent = "How do you document your APIs?",
                            SenderId = "seed-user-cpw-235-3"
                        },
                        new
                        {
                            Id = 46,
                            ChannelId = 1,
                            CreatedAt = new DateTime(2024, 11, 3, 11, 0, 0, 0, DateTimeKind.Utc),
                            MessageContent = "Share a tip for writing better commit messages.",
                            SenderId = "seed-user-cpw-235-4"
                        },
                        new
                        {
                            Id = 47,
                            ChannelId = 1,
                            CreatedAt = new DateTime(2024, 11, 3, 11, 4, 0, 0, DateTimeKind.Utc),
                            MessageContent = "What database topic should we revisit?",
                            SenderId = "seed-user-cpw-235-5"
                        },
                        new
                        {
                            Id = 48,
                            ChannelId = 1,
                            CreatedAt = new DateTime(2024, 11, 3, 11, 8, 0, 0, DateTimeKind.Utc),
                            MessageContent = "How do you stay motivated on long assignments?",
                            SenderId = "seed-user-cpw-235-6"
                        },
                        new
                        {
                            Id = 49,
                            ChannelId = 1,
                            CreatedAt = new DateTime(2024, 11, 3, 11, 12, 0, 0, DateTimeKind.Utc),
                            MessageContent = "Post a question you think others might have too.",
                            SenderId = "seed-user-cpw-235"
                        },
                        new
                        {
                            Id = 50,
                            ChannelId = 1,
                            CreatedAt = new DateTime(2024, 11, 3, 11, 16, 0, 0, DateTimeKind.Utc),
                            MessageContent = "Welcome to CPW 235! Share what you want to learn this quarter.",
                            SenderId = "seed-user-cpw-235-2"
                        },
                        new
                        {
                            Id = 51,
                            ChannelId = 2,
                            CreatedAt = new DateTime(2024, 11, 4, 9, 0, 0, 0, DateTimeKind.Utc),
                            MessageContent = "Routing and attribute routes feel clearer now.",
                            SenderId = "seed-user-cpw-235-2"
                        },
                        new
                        {
                            Id = 52,
                            ChannelId = 2,
                            CreatedAt = new DateTime(2024, 11, 4, 9, 5, 0, 0, DateTimeKind.Utc),
                            MessageContent = "Remember to register SignalR in Program.cs.",
                            SenderId = "seed-user-cpw-235-3"
                        },
                        new
                        {
                            Id = 53,
                            ChannelId = 2,
                            CreatedAt = new DateTime(2024, 11, 4, 9, 10, 0, 0, DateTimeKind.Utc),
                            MessageContent = "Add logging to controller actions while debugging.",
                            SenderId = "seed-user-cpw-235-4"
                        },
                        new
                        {
                            Id = 54,
                            ChannelId = 2,
                            CreatedAt = new DateTime(2024, 11, 4, 9, 15, 0, 0, DateTimeKind.Utc),
                            MessageContent = "Identity scaffolding saved a ton of time.",
                            SenderId = "seed-user-cpw-235-5"
                        },
                        new
                        {
                            Id = 55,
                            ChannelId = 2,
                            CreatedAt = new DateTime(2024, 11, 4, 9, 20, 0, 0, DateTimeKind.Utc),
                            MessageContent = "Static files need cache busting—enable versioning.",
                            SenderId = "seed-user-cpw-235-6"
                        },
                        new
                        {
                            Id = 56,
                            ChannelId = 2,
                            CreatedAt = new DateTime(2024, 11, 4, 9, 25, 0, 0, DateTimeKind.Utc),
                            MessageContent = "Partial views keep the layout clean.",
                            SenderId = "seed-user-cpw-235"
                        },
                        new
                        {
                            Id = 57,
                            ChannelId = 2,
                            CreatedAt = new DateTime(2024, 11, 4, 9, 30, 0, 0, DateTimeKind.Utc),
                            MessageContent = "Model validation attributes caught my bug.",
                            SenderId = "seed-user-cpw-235-2"
                        },
                        new
                        {
                            Id = 58,
                            ChannelId = 2,
                            CreatedAt = new DateTime(2024, 11, 4, 9, 35, 0, 0, DateTimeKind.Utc),
                            MessageContent = "DI setup: keep services in Program.cs tidy.",
                            SenderId = "seed-user-cpw-235-3"
                        },
                        new
                        {
                            Id = 59,
                            ChannelId = 2,
                            CreatedAt = new DateTime(2024, 11, 4, 9, 40, 0, 0, DateTimeKind.Utc),
                            MessageContent = "Swagger UI helps test quickly.",
                            SenderId = "seed-user-cpw-235-4"
                        },
                        new
                        {
                            Id = 60,
                            ChannelId = 2,
                            CreatedAt = new DateTime(2024, 11, 4, 9, 45, 0, 0, DateTimeKind.Utc),
                            MessageContent = "Remember to check appsettings.Development.json.",
                            SenderId = "seed-user-cpw-235-5"
                        },
                        new
                        {
                            Id = 61,
                            ChannelId = 3,
                            CreatedAt = new DateTime(2024, 11, 5, 10, 0, 0, 0, DateTimeKind.Utc),
                            MessageContent = "Interfaces finally clicked today.",
                            SenderId = "seed-user-cpw-235-3"
                        },
                        new
                        {
                            Id = 62,
                            ChannelId = 3,
                            CreatedAt = new DateTime(2024, 11, 5, 10, 6, 0, 0, DateTimeKind.Utc),
                            MessageContent = "LINQ query syntax vs method syntax—team method.",
                            SenderId = "seed-user-cpw-235-4"
                        },
                        new
                        {
                            Id = 63,
                            ChannelId = 3,
                            CreatedAt = new DateTime(2024, 11, 5, 10, 12, 0, 0, DateTimeKind.Utc),
                            MessageContent = "Records are great for DTOs.",
                            SenderId = "seed-user-cpw-235-5"
                        },
                        new
                        {
                            Id = 64,
                            ChannelId = 3,
                            CreatedAt = new DateTime(2024, 11, 5, 10, 18, 0, 0, DateTimeKind.Utc),
                            MessageContent = "Pattern matching made my switch smaller.",
                            SenderId = "seed-user-cpw-235-6"
                        },
                        new
                        {
                            Id = 65,
                            ChannelId = 3,
                            CreatedAt = new DateTime(2024, 11, 5, 10, 24, 0, 0, DateTimeKind.Utc),
                            MessageContent = "Nullable reference types caught a null bug.",
                            SenderId = "seed-user-cpw-235"
                        },
                        new
                        {
                            Id = 66,
                            ChannelId = 3,
                            CreatedAt = new DateTime(2024, 11, 5, 10, 30, 0, 0, DateTimeKind.Utc),
                            MessageContent = "Async/await still trips me up.",
                            SenderId = "seed-user-cpw-235-2"
                        },
                        new
                        {
                            Id = 67,
                            ChannelId = 3,
                            CreatedAt = new DateTime(2024, 11, 5, 10, 36, 0, 0, DateTimeKind.Utc),
                            MessageContent = "Extension methods keep helpers organized.",
                            SenderId = "seed-user-cpw-235-3"
                        },
                        new
                        {
                            Id = 68,
                            ChannelId = 3,
                            CreatedAt = new DateTime(2024, 11, 5, 10, 42, 0, 0, DateTimeKind.Utc),
                            MessageContent = "String interpolation over concatenation any day.",
                            SenderId = "seed-user-cpw-235-4"
                        },
                        new
                        {
                            Id = 69,
                            ChannelId = 3,
                            CreatedAt = new DateTime(2024, 11, 5, 10, 48, 0, 0, DateTimeKind.Utc),
                            MessageContent = "Use var judiciously; clarity first.",
                            SenderId = "seed-user-cpw-235-5"
                        },
                        new
                        {
                            Id = 70,
                            ChannelId = 3,
                            CreatedAt = new DateTime(2024, 11, 5, 10, 54, 0, 0, DateTimeKind.Utc),
                            MessageContent = "xml comments help IntelliSense a lot.",
                            SenderId = "seed-user-cpw-235-6"
                        },
                        new
                        {
                            Id = 71,
                            ChannelId = 4,
                            CreatedAt = new DateTime(2024, 11, 6, 11, 0, 0, 0, DateTimeKind.Utc),
                            MessageContent = "Queues vs stacks: when would you pick each?",
                            SenderId = "seed-user-cpw-235-4"
                        },
                        new
                        {
                            Id = 72,
                            ChannelId = 4,
                            CreatedAt = new DateTime(2024, 11, 6, 11, 7, 0, 0, DateTimeKind.Utc),
                            MessageContent = "Binary search trees feel elegant.",
                            SenderId = "seed-user-cpw-235-5"
                        },
                        new
                        {
                            Id = 73,
                            ChannelId = 4,
                            CreatedAt = new DateTime(2024, 11, 6, 11, 14, 0, 0, DateTimeKind.Utc),
                            MessageContent = "Linked lists are great for constant-time inserts.",
                            SenderId = "seed-user-cpw-235-6"
                        },
                        new
                        {
                            Id = 74,
                            ChannelId = 4,
                            CreatedAt = new DateTime(2024, 11, 6, 11, 21, 0, 0, DateTimeKind.Utc),
                            MessageContent = "Hash sets saved me from duplicates.",
                            SenderId = "seed-user-cpw-235"
                        },
                        new
                        {
                            Id = 75,
                            ChannelId = 4,
                            CreatedAt = new DateTime(2024, 11, 6, 11, 28, 0, 0, DateTimeKind.Utc),
                            MessageContent = "Graph traversal with BFS felt natural.",
                            SenderId = "seed-user-cpw-235-2"
                        },
                        new
                        {
                            Id = 76,
                            ChannelId = 4,
                            CreatedAt = new DateTime(2024, 11, 6, 11, 35, 0, 0, DateTimeKind.Utc),
                            MessageContent = "DFS recursion depth is a gotcha.",
                            SenderId = "seed-user-cpw-235-3"
                        },
                        new
                        {
                            Id = 77,
                            ChannelId = 4,
                            CreatedAt = new DateTime(2024, 11, 6, 11, 42, 0, 0, DateTimeKind.Utc),
                            MessageContent = "Big-O cheat sheet taped to my monitor.",
                            SenderId = "seed-user-cpw-235-4"
                        },
                        new
                        {
                            Id = 78,
                            ChannelId = 4,
                            CreatedAt = new DateTime(2024, 11, 6, 11, 49, 0, 0, DateTimeKind.Utc),
                            MessageContent = "Priority queues make scheduling easier.",
                            SenderId = "seed-user-cpw-235-5"
                        },
                        new
                        {
                            Id = 79,
                            ChannelId = 4,
                            CreatedAt = new DateTime(2024, 11, 6, 11, 56, 0, 0, DateTimeKind.Utc),
                            MessageContent = "Topological sort finally clicked!",
                            SenderId = "seed-user-cpw-235-6"
                        },
                        new
                        {
                            Id = 80,
                            ChannelId = 4,
                            CreatedAt = new DateTime(2024, 11, 6, 12, 3, 0, 0, DateTimeKind.Utc),
                            MessageContent = "Two-pointer patterns help in arrays.",
                            SenderId = "seed-user-cpw-235"
                        });
                });

            modelBuilder.Entity("Corkboard.Models.Server", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("IconUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastMessageTimeStamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PrivacyLevel")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Servers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 11, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Class discussion space for ASP.NET and computer science topics.",
                            Name = "CPW 235",
                            OwnerId = "seed-user-cpw-235",
                            PrivacyLevel = 0
                        });
                });

            modelBuilder.Entity("Corkboard.Models.ServerInvite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedById")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("InviteCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("InvitedUserId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("OneTimeUse")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ServerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TimesUsed")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("InviteCode")
                        .IsUnique();

                    b.HasIndex("InvitedUserId");

                    b.HasIndex("ServerId");

                    b.ToTable("ServerInvites");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 11, 1, 12, 30, 0, 0, DateTimeKind.Utc),
                            CreatedById = "seed-user-cpw-235",
                            InviteCode = "CPW235-TEST",
                            IsUsed = false,
                            OneTimeUse = false,
                            ServerId = 1,
                            TimesUsed = 0
                        });
                });

            modelBuilder.Entity("Corkboard.Models.ServerMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("InviteId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasMaxLength(50)
                        .HasColumnType("INTEGER");

                    b.Property<int>("ServerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("InviteId");

                    b.HasIndex("UserId");

                    b.HasIndex("ServerId", "UserId")
                        .IsUnique();

                    b.ToTable("ServerMembers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            JoinedAt = new DateTime(2024, 11, 1, 12, 5, 0, 0, DateTimeKind.Utc),
                            Role = 2,
                            ServerId = 1,
                            UserId = "seed-user-cpw-235"
                        },
                        new
                        {
                            Id = 2,
                            JoinedAt = new DateTime(2024, 11, 2, 9, 0, 0, 0, DateTimeKind.Utc),
                            Role = 0,
                            ServerId = 1,
                            UserId = "seed-user-cpw-235-2"
                        },
                        new
                        {
                            Id = 3,
                            JoinedAt = new DateTime(2024, 11, 2, 9, 5, 0, 0, DateTimeKind.Utc),
                            Role = 0,
                            ServerId = 1,
                            UserId = "seed-user-cpw-235-3"
                        },
                        new
                        {
                            Id = 4,
                            JoinedAt = new DateTime(2024, 11, 2, 9, 10, 0, 0, DateTimeKind.Utc),
                            Role = 0,
                            ServerId = 1,
                            UserId = "seed-user-cpw-235-4"
                        },
                        new
                        {
                            Id = 5,
                            JoinedAt = new DateTime(2024, 11, 2, 9, 15, 0, 0, DateTimeKind.Utc),
                            Role = 0,
                            ServerId = 1,
                            UserId = "seed-user-cpw-235-5"
                        },
                        new
                        {
                            Id = 6,
                            JoinedAt = new DateTime(2024, 11, 2, 9, 20, 0, 0, DateTimeKind.Utc),
                            Role = 0,
                            ServerId = 1,
                            UserId = "seed-user-cpw-235-6"
                        });
                });

            modelBuilder.Entity("Corkboard.Models.UserAccount", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Bio")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FullName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("Major")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProfilePictureUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "seed-user-cpw-235",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "seed-concurrency-stamp",
                            Email = "cpw.owner@example.com",
                            EmailConfirmed = true,
                            FullName = "CPW Owner",
                            LockoutEnabled = false,
                            Major = "Computer Science",
                            NormalizedEmail = "CPW.OWNER@EXAMPLE.COM",
                            NormalizedUserName = "CPW.OWNER",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "seed-security-stamp",
                            TwoFactorEnabled = false,
                            UserName = "cpw.owner"
                        },
                        new
                        {
                            Id = "seed-user-cpw-235-2",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "seed-concurrency-stamp",
                            Email = "cpw.student@example.com",
                            EmailConfirmed = true,
                            FullName = "CPW Student One",
                            LockoutEnabled = false,
                            Major = "Computer Science",
                            NormalizedEmail = "CPW.STUDENT@EXAMPLE.COM",
                            NormalizedUserName = "CPW.STUDENT",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "seed-security-stamp",
                            TwoFactorEnabled = false,
                            UserName = "cpw.student"
                        },
                        new
                        {
                            Id = "seed-user-cpw-235-3",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "seed-concurrency-stamp",
                            Email = "cpw.student.two@example.com",
                            EmailConfirmed = true,
                            FullName = "CPW Student Two",
                            LockoutEnabled = false,
                            Major = "Computer Science",
                            NormalizedEmail = "CPW.STUDENT.TWO@EXAMPLE.COM",
                            NormalizedUserName = "CPW.STUDENT.TWO",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "seed-security-stamp",
                            TwoFactorEnabled = false,
                            UserName = "cpw.student.two"
                        },
                        new
                        {
                            Id = "seed-user-cpw-235-4",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "seed-concurrency-stamp",
                            Email = "cpw.student.three@example.com",
                            EmailConfirmed = true,
                            FullName = "CPW Student Three",
                            LockoutEnabled = false,
                            Major = "Software Engineering",
                            NormalizedEmail = "CPW.STUDENT.THREE@EXAMPLE.COM",
                            NormalizedUserName = "CPW.STUDENT.THREE",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "seed-security-stamp",
                            TwoFactorEnabled = false,
                            UserName = "cpw.student.three"
                        },
                        new
                        {
                            Id = "seed-user-cpw-235-5",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "seed-concurrency-stamp",
                            Email = "cpw.student.four@example.com",
                            EmailConfirmed = true,
                            FullName = "CPW Student Four",
                            LockoutEnabled = false,
                            Major = "Information Systems",
                            NormalizedEmail = "CPW.STUDENT.FOUR@EXAMPLE.COM",
                            NormalizedUserName = "CPW.STUDENT.FOUR",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "seed-security-stamp",
                            TwoFactorEnabled = false,
                            UserName = "cpw.student.four"
                        },
                        new
                        {
                            Id = "seed-user-cpw-235-6",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "seed-concurrency-stamp",
                            Email = "cpw.student.five@example.com",
                            EmailConfirmed = true,
                            FullName = "CPW Student Five",
                            LockoutEnabled = false,
                            Major = "Computer Engineering",
                            NormalizedEmail = "CPW.STUDENT.FIVE@EXAMPLE.COM",
                            NormalizedUserName = "CPW.STUDENT.FIVE",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "seed-security-stamp",
                            TwoFactorEnabled = false,
                            UserName = "cpw.student.five"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Corkboard.Models.Channel", b =>
                {
                    b.HasOne("Corkboard.Models.Server", "Server")
                        .WithMany("Channels")
                        .HasForeignKey("ServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Server");
                });

            modelBuilder.Entity("Corkboard.Models.Message", b =>
                {
                    b.HasOne("Corkboard.Models.Channel", "Channel")
                        .WithMany("Messages")
                        .HasForeignKey("ChannelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Corkboard.Models.UserAccount", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Channel");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("Corkboard.Models.Server", b =>
                {
                    b.HasOne("Corkboard.Models.UserAccount", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Corkboard.Models.ServerInvite", b =>
                {
                    b.HasOne("Corkboard.Models.UserAccount", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Corkboard.Models.UserAccount", "InvitedUser")
                        .WithMany()
                        .HasForeignKey("InvitedUserId");

                    b.HasOne("Corkboard.Models.Server", "Server")
                        .WithMany()
                        .HasForeignKey("ServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("InvitedUser");

                    b.Navigation("Server");
                });

            modelBuilder.Entity("Corkboard.Models.ServerMember", b =>
                {
                    b.HasOne("Corkboard.Models.ServerInvite", "Invite")
                        .WithMany("CreatedMemberships")
                        .HasForeignKey("InviteId");

                    b.HasOne("Corkboard.Models.Server", "Server")
                        .WithMany("Members")
                        .HasForeignKey("ServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Corkboard.Models.UserAccount", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Invite");

                    b.Navigation("Server");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Corkboard.Models.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Corkboard.Models.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Corkboard.Models.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Corkboard.Models.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Corkboard.Models.Channel", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("Corkboard.Models.Server", b =>
                {
                    b.Navigation("Channels");

                    b.Navigation("Members");
                });

            modelBuilder.Entity("Corkboard.Models.ServerInvite", b =>
                {
                    b.Navigation("CreatedMemberships");
                });
#pragma warning restore 612, 618
        }
    }
}
